INSERT INTO `product` (`name`, image, price, stock, category, description) VALUES
('Monitor Samsung 24"', 'https://tccommercear.vtexassets.com/arquivos/ids/161111/159696-800-auto.png', 199.99, 20, 'Pantallas', 'Monitor LED de 24 pulgadas con resolución Full HD.'),
('Auriculares Bluetooth JBL', 'https://noblex.com.ar/media/wysiwyg/Noblex_AURI.jpg', 59.90, 50, 'Audio', 'Auriculares inalámbricos con sonido puro y diseño ergonómico.'),
('Teclado Mecánico Redragon', 'https://app.contabilium.com/files/explorer/20302/Productos-Servicios/concepto-5400544.jpg', 89.90, 30, 'Accesorios', 'Teclado mecánico retroiluminado ideal para gaming.'),
('Mouse Logitech M170', 'https://www.xt-pc.com.ar/img/productos/14/MOU998.jpg', 15.00, 100, 'Accesorios', 'Mouse inalámbrico compacto, ideal para uso diario.'),
('Notebook Lenovo IdeaPad 3', 'https://http2.mlstatic.com/D_NQ_NP_736965-MLA80837699490_122024-O.webp', 749.99, 12, 'Computación', 'Notebook con procesador Intel i5, 8GB RAM y SSD de 256GB.'),
('Smartphone Galaxy A14', 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSO2wR77A2lknJf17CtfDtgIiKZtg3LzQhRrJ8PqRRRq8pDVXBL2No_djy_OUa9LnMDtsuQ6CoVBAMDkNSWO5Y0UFD1J_XKup80FiQWxNw', 179.99, 25, 'Tecnología', 'Smartphone de gama media con cámara cuádruple y batería de larga duración.'),
('Tablet Samsung Galaxy Tab A8', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQq8yZ0VdTuv-rWoMDqRv8uZdsFe8OdoVA1pA&s', 229.00, 15, 'Tecnología', 'Tablet de 10.5 pulgadas con excelente rendimiento multimedia.'),
('Impresora HP DeskJet 2710', 'https://hp.widen.net/content/ada6tccenx/png/ada6tccenx.png?w=800&h=600&dpi=72&color=ffffff00', 89.99, 18, 'Oficina', 'Impresora multifunción inalámbrica para el hogar o la oficina.'),
('Disco SSD Kingston 480GB', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJ41xeBCKI0Q_IOl98qAtEenNq3AXgYGLgoA&s', 49.99, 40, 'Almacenamiento', 'Disco de estado sólido con alta velocidad de lectura y escritura.'),
('Parlante Portátil Sony SRS-XB13', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfXr9Znmu_oZh8zYYKobm_3yCaZkK3pyVBcA&s', 69.99, 22, 'Audio', 'Parlante bluetooth resistente al agua con extra bass.');